# Generated by Django 5.2 on 2025-05-01 21:11

import bot.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=32, unique=True, verbose_name='Telegram ID')),
                ('code', models.CharField(default=bot.utils.generate_otp, max_length=16, verbose_name='OTP Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
